title: SkyLectures
description: AI, Data Engineering, Programming Lecture Materials

url: "https://skylectures.github.io"
baseurl: ""

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  lectlog:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: page

sass:
  sass_dir: _sass